# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_code_810'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempstatus810',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Code', models.CharField(max_length=1000)),
                ('Division_Code', models.CharField(max_length=1000)),
                ('Record_Number', models.CharField(max_length=1000)),
                ('Customer_Number', models.CharField(max_length=1000)),
                ('Customer_Purchase_Order_Number', models.CharField(max_length=1000)),
                ('DATE_INVOICED', models.CharField(max_length=1000)),
                ('DATE_CREATED', models.CharField(max_length=1000)),
                ('DOCTYPE', models.CharField(max_length=1000)),
                ('REMARKS', models.CharField(max_length=1000)),
            ],
        ),
    ]
